### ISSUE TITLE
Reference for all category pages?

### ISSUE THREAD

**Issue by tohuw** [octopress/category-index#2]
I'm trying, with my limited Ruby grokking capabilities, to understand how this plugin works in terms of variables and elements usable in Liquid templates. I've noticed the category pages appear in site.pages, but is there some specific reference for all category pages? Similarly, is there some way to refer to all pages that aren't category pages?

Lastly, for whatever reason, the links to category pages build as e.g. //topics/testcat/index.html, given the below config. I imagine I've done something incorrectly.

```
category_dir: topics
prefixes:
  title: ""
  meta_description: "Topic: "
feed:
  enabled: false
  count: 5
```
